[build.environment]
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"
[functions]
  directory = "my_functions"

[build]
  # The base directory for the build, relative to the repository root.
  base = "."

  # The directory where the build output is stored.
  publish = "public"

  # The command that Netlify uses to build your site.
  command = "npm run build"

[build.environment]
  # Set environment variables for your build process.
  NODE_ENV = "production"

[[plugins]]
  # Optionally add plugins here for advanced features.
  package = "@netlify/plugin-sitemap"
